### ISSUE TITLE
Password check for similar account information is case sensitive (bug)

### ISSUE THREAD

**Issue by sahilfaizal01** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#152]
username: test_1
password: TeSt567*1

password gets successfully changed, so suggested to make it case in-sensitive

**Comment by agoluoglu** [comment]
Hi @sahilfaizal01 , I am not sure I understand your comment, can you clarify? Passwords should be case sensitive. As far as I can tell, your example has a valid password.

**Comment by agoluoglu** [comment]
Didn't get a response and based on our understanding this works as intended @sahilfaizal01 , closing
