### ISSUE TITLE
Search functionality issue (bug)

### ISSUE THREAD

**Issue by sahilfaizal01** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#153]
A single character like 'z' is getting matched with post-content rather than post-title matching. It would provide filtered search content to the user.

**Comment by agoluoglu** [comment]
Hi @sahilfaizal01 , I am closing this issue because this is an intentional feature. As stated in our document, the discovery page "searches based on words in a post’s title or description". We want to return results that match the post's content in addition to a post's title.
