### ISSUE TITLE
Unable to login with assigned username and password for team 1

### ISSUE THREAD

**Issue by ManaliTanna** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#157]
The assigned username and password for team 1 is:
username: test_1
password: knowledgeable-needle

But I'm getting an error " Please enter a correct username and password. Note that both fields may be case-sensitive." and not able to login

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOERpQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--86f6d25a53c9e7bea41f9e906f2f3108a17d9b8e/image.png)

**Comment by ManaliTanna** [comment]
Although, I am able to sign up with those credentials. Was that the intention? For testers to create accounts with the given credentials?

**Comment by agoluoglu** [comment]
Hi @ManaliTanna , I believe this is because one of your teammates changed the password to your team's account. Can you confirm with your teammates?
