### ISSUE TITLE
Blank Fields in 'Edit Post' Feature

### ISSUE THREAD

**Issue by ll4407** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#160]
When navigating to the 'Edit Profile' feature, I noticed that the 'Title' and 'Description' fields are empty, devoid of the existing post content. Ideally, these fields should be pre-populated with the current post's details, allowing for easy editing and adjustments, rather than having to rewrite from scratch.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHZvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26cd6cd0ae3156647e7a5de81dbf51412767955/Screenshot%202023-11-17%20at%2012.27.16%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHpvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7cf3c6a7c2eb7e798328ce3310511d62de64d04/Screenshot%202023-11-17%20at%2012.34.55%E2%80%AFPM.png)

**Comment by agoluoglu** [comment]
Hi @ll4407 , I am closing this issue because it is specifically listed in our document under the What Doesn't Work section: "When editing a post, the form is not pre-populated with the post’s current title and description."
This has not been implemented yet and is in our backlog already.
