### ISSUE TITLE
Can Create an Empty Post and the post cannot be clicked on, shows up on the home page, and cannot be removed

### ISSUE THREAD

**Issue by rg4352** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#161]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWpwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3233b615e7d3a308f1f1843169df6dc0c080f36/Screenshot%202023-11-17%20at%208.24.40%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW5wQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7fe35b997d77edb75d81343937a27bcc5151933a/Screenshot%202023-11-17%20at%208.24.54%E2%80%AFPM.png)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXJwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--66b4e3eff2daf65edb9d226ef89ffb8120650b49/Screenshot%202023-11-17%20at%208.28.02%E2%80%AFPM.png)

**Comment by rg4352** [comment]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXZwQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--24e9adf8e926e8e119fda05cca1fc70e690394ed/Screenshot%202023-11-17%20at%208.44.00%E2%80%AFPM.png)

Same goes for keeping the post in the drafts

**Comment by rg4352** [comment]
This was done by putting an " " into the description and title

**Comment by utsavoza** [comment]
Thanks! Should be fixed with #245
