### ISSUE TITLE
Making a draft public

### ISSUE THREAD

**Issue by jayjayh** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#162]
Can not publish a draft post on the view post page

![image](https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-2/assets/26288542/56f9c81d-d960-4b2a-af5d-2d1675bc2185)

**Comment by jayjayh** [comment]
Since editing the post does not populate the fields having a post on this page helps

**Comment by agoluoglu** [comment]
Hi, you have to edit the draft (click Edit) to be able to publish it.
