### ISSUE TITLE
The same person can send multiple connections

### ISSUE THREAD

**Issue by jayjayh** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#163]
![image](https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-2/assets/26288542/d993d1c8-b807-4f9f-913b-99315ded3c31)

**Comment by jayjayh** [comment]
![image](https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-2/assets/26288542/dca1f42a-b767-40d8-ab39-991676f80eb9)
Clicking it will give an error

**Comment by jayjayh** [comment]
For context ive already accepted the request before

**Comment by agoluoglu** [comment]
Hi @jayjayh , this is stated in our Doesn’t Work section “ After you accept a connection, the notification still has a clickable Accept button. If you click this, it will try to connect again and error.”
