### ISSUE TITLE
Clicking clear also searches

### ISSUE THREAD

**Issue by jayjayh** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#164]
https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-2/assets/26288542/fc07c33c-c82f-492d-bcde-2bf2a5b72b40

**Comment by agoluoglu** [comment]
Hi @jayjayh , this is listed in the Doesn’t Work section of our document “If you type in the search bar and click “Clear” instead of “Search”, it will still search.”
