### ISSUE TITLE
 Post draft is not properly loaded

### ISSUE THREAD

**Issue by SoyMark** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#166]
It's great to let users to save drafts of their posts. I can see my draft in my profile, but after I click `edit` button, previously entered content has all disappeared. To make it functional, you can load the content in the input box
<img width="510" alt="image" src="https://github.com/gcivil-nyu-org/INET-Monday-Fall2023-Team-2/assets/65658776/ae873293-db8d-4b98-9653-c41f2845b252">

**Comment by agoluoglu** [comment]
Hi @SoyMark , this is included in the Doesn’t Work section of our document “ When editing a post, the form is not pre-populated with the post’s current title and description”
