### ISSUE TITLE
As a user, I want to browse through categories of posts tailored to my profile on my Discovery page so that I can explore a wider range of posts than my Home page offers.

### ISSUE THREAD

**Issue by MJ3128** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#28]
As a user, I want to browse through categories of posts tailored to my profile on my Discovery page so that I can explore a wider range of posts than my Home page offers.

Acceptance Criteria:

- [ ] Users can view recommended categories (tags, interests, etc.) on their Discovery page.
- [ ] Recommended categories on the Discovery page are generated based on the user's profile information such as tagged interests as well as the app's most popular and most recent posts.
- [ ] Users can click on a category to view a feed of posts in that category.
- [x] Posts are displayed with relevant details such as activity, location, time, and user.

**Comment by agoluoglu** [comment]
reprioritization of finalizing details on existing features meant cutting out the feature of categories in the discovery ui
