### ISSUE TITLE
As a user, I want to be able to publicly interact with a poster and other users through a post's comment section.

### ISSUE THREAD

**Issue by MJ3128** [gcivil-nyu-org/INET-Monday-Fall2023-Team-2#29]
As a user, I want to be able to publicly interact with a poster and other users through a post's comment section.

Acceptance criteria:

- [x] Users can write and post comments on posts.
- [ ] Users can edit their own comments on posts.
- [x] Users can delete their own comments from posts.
- [x] Users can mention users in comments.

**Comment by agoluoglu** [comment]
decided to not include editing comment as a feature after examining other applications
